### ISSUE TITLE
add support for _command inside dictionary parameter

### ISSUE THREAD

**Issue by alexnsl** [alexnsl/hwswa2#107]
Originally reported by: **Andrey Kartashov (Bitbucket: [gorilych](http://bitbucket.org/gorilych), GitHub: [gorilych](http://github.com/gorilych))**

---

```
#!yaml

param-name:
  _type: dictionary
  _keys: [key1, key2, key3]
  _separator: ' '
  _command: get-keys-command
```

---
- Bitbucket: https://bitbucket.org/gorilych/hwswa2/issue/107
